#define Java_ej_bon_XMath_limit__III _java_Lej_bon_XMath_method_limit_I_I_I_I,3,73ll
extern JavaMethodRef _java_Lej_bon_XMath_method_limit_I_I_I_I ;
#define Java_ej_bon_XMath_limit__FFF _java_Lej_bon_XMath_method_limit_F_F_F_F,3,292ll
extern JavaMethodRef _java_Lej_bon_XMath_method_limit_F_F_F_F ;
#define Java_ej_bon_XMath_limit__JJJ _java_Lej_bon_XMath_method_limit_J_J_J_J,3,146ll
extern JavaMethodRef _java_Lej_bon_XMath_method_limit_J_J_J_J ;
#define Java_ej_bon_XMath_limit__DDD _java_Lej_bon_XMath_method_limit_D_D_D_D,3,219ll
extern JavaMethodRef _java_Lej_bon_XMath_method_limit_D_D_D_D ;
#define Java_ej_bon_XMath_abs__D _java_Lej_bon_XMath_method_abs_D_D,1,3ll
extern JavaMethodRef _java_Lej_bon_XMath_method_abs_D_D ;
#define Java_ej_bon_XMath_abs__F _java_Lej_bon_XMath_method_abs_F_F,1,4ll
extern JavaMethodRef _java_Lej_bon_XMath_method_abs_F_F ;
#define Java_ej_bon_XMath_abs__I _java_Lej_bon_XMath_method_abs_I_I,1,1ll
extern JavaMethodRef _java_Lej_bon_XMath_method_abs_I_I ;
#define Java_ej_bon_XMath_abs__J _java_Lej_bon_XMath_method_abs_J_J,1,2ll
extern JavaMethodRef _java_Lej_bon_XMath_method_abs_J_J ;
#define Java_ej_bon_XMath_ceil _java_Lej_bon_XMath_method_ceil_D_D,1,3ll
extern JavaMethodRef _java_Lej_bon_XMath_method_ceil_D_D ;
#define Java_ej_bon_XMath_cos _java_Lej_bon_XMath_method_cos_D_D,1,3ll
extern JavaMethodRef _java_Lej_bon_XMath_method_cos_D_D ;
#define Java_ej_bon_XMath_floor _java_Lej_bon_XMath_method_floor_D_D,1,3ll
extern JavaMethodRef _java_Lej_bon_XMath_method_floor_D_D ;
#define Java_ej_bon_XMath_max__DD _java_Lej_bon_XMath_method_max_D_D_D,2,27ll
extern JavaMethodRef _java_Lej_bon_XMath_method_max_D_D_D ;
#define Java_ej_bon_XMath_max__FF _java_Lej_bon_XMath_method_max_F_F_F,2,36ll
extern JavaMethodRef _java_Lej_bon_XMath_method_max_F_F_F ;
#define Java_ej_bon_XMath_max__JJ _java_Lej_bon_XMath_method_max_J_J_J,2,18ll
extern JavaMethodRef _java_Lej_bon_XMath_method_max_J_J_J ;
#define Java_ej_bon_XMath_max__II _java_Lej_bon_XMath_method_max_I_I_I,2,9ll
extern JavaMethodRef _java_Lej_bon_XMath_method_max_I_I_I ;
#define Java_ej_bon_XMath_min__DD _java_Lej_bon_XMath_method_min_D_D_D,2,27ll
extern JavaMethodRef _java_Lej_bon_XMath_method_min_D_D_D ;
#define Java_ej_bon_XMath_min__FF _java_Lej_bon_XMath_method_min_F_F_F,2,36ll
extern JavaMethodRef _java_Lej_bon_XMath_method_min_F_F_F ;
#define Java_ej_bon_XMath_min__II _java_Lej_bon_XMath_method_min_I_I_I,2,9ll
extern JavaMethodRef _java_Lej_bon_XMath_method_min_I_I_I ;
#define Java_ej_bon_XMath_min__JJ _java_Lej_bon_XMath_method_min_J_J_J,2,18ll
extern JavaMethodRef _java_Lej_bon_XMath_method_min_J_J_J ;
#define Java_ej_bon_XMath_sin _java_Lej_bon_XMath_method_sin_D_D,1,3ll
extern JavaMethodRef _java_Lej_bon_XMath_method_sin_D_D ;
#define Java_ej_bon_XMath_sqrt _java_Lej_bon_XMath_method_sqrt_D_D,1,3ll
extern JavaMethodRef _java_Lej_bon_XMath_method_sqrt_D_D ;
#define Java_ej_bon_XMath_tan _java_Lej_bon_XMath_method_tan_D_D,1,3ll
extern JavaMethodRef _java_Lej_bon_XMath_method_tan_D_D ;
#define Java_ej_bon_XMath_toDegrees _java_Lej_bon_XMath_method_toDegrees_D_D,1,3ll
extern JavaMethodRef _java_Lej_bon_XMath_method_toDegrees_D_D ;
#define Java_ej_bon_XMath_toRadians _java_Lej_bon_XMath_method_toRadians_D_D,1,3ll
extern JavaMethodRef _java_Lej_bon_XMath_method_toRadians_D_D ;
#define Java_java_lang_System_exit _java_Ljava_lang_System_method_exit_I_V,1,1ll
extern JavaMethodRef _java_Ljava_lang_System_method_exit_I_V ;
#define Java_java_lang_System_gc _java_Ljava_lang_System_method_gc_V,0,0ll
extern JavaMethodRef _java_Ljava_lang_System_method_gc_V ;
#define Java_java_lang_Math_abs__D _java_Ljava_lang_Math_method_abs_D_D,1,3ll
extern JavaMethodRef _java_Ljava_lang_Math_method_abs_D_D ;
#define Java_java_lang_Math_abs__F _java_Ljava_lang_Math_method_abs_F_F,1,4ll
extern JavaMethodRef _java_Ljava_lang_Math_method_abs_F_F ;
#define Java_java_lang_Math_abs__J _java_Ljava_lang_Math_method_abs_J_J,1,2ll
extern JavaMethodRef _java_Ljava_lang_Math_method_abs_J_J ;
#define Java_java_lang_Math_copySign__DD _java_Ljava_lang_Math_method_copySign_D_D_D,2,27ll
extern JavaMethodRef _java_Ljava_lang_Math_method_copySign_D_D_D ;
#define Java_java_lang_Math_copySign__FF _java_Ljava_lang_Math_method_copySign_F_F_F,2,36ll
extern JavaMethodRef _java_Ljava_lang_Math_method_copySign_F_F_F ;
#define Java_java_lang_Math_getExponent__D _java_Ljava_lang_Math_method_getExponent_D_I,1,3ll
extern JavaMethodRef _java_Ljava_lang_Math_method_getExponent_D_I ;
#define Java_java_lang_Math_getExponent__F _java_Ljava_lang_Math_method_getExponent_F_I,1,4ll
extern JavaMethodRef _java_Ljava_lang_Math_method_getExponent_F_I ;
#define Java_java_lang_Math_max__DD _java_Ljava_lang_Math_method_max_D_D_D,2,27ll
extern JavaMethodRef _java_Ljava_lang_Math_method_max_D_D_D ;
#define Java_java_lang_Math_max__FF _java_Ljava_lang_Math_method_max_F_F_F,2,36ll
extern JavaMethodRef _java_Ljava_lang_Math_method_max_F_F_F ;
#define Java_java_lang_Math_max__JJ _java_Ljava_lang_Math_method_max_J_J_J,2,18ll
extern JavaMethodRef _java_Ljava_lang_Math_method_max_J_J_J ;
#define Java_java_lang_Math_min__DD _java_Ljava_lang_Math_method_min_D_D_D,2,27ll
extern JavaMethodRef _java_Ljava_lang_Math_method_min_D_D_D ;
#define Java_java_lang_Math_min__FF _java_Ljava_lang_Math_method_min_F_F_F,2,36ll
extern JavaMethodRef _java_Ljava_lang_Math_method_min_F_F_F ;
#define Java_java_lang_Math_min__JJ _java_Ljava_lang_Math_method_min_J_J_J,2,18ll
extern JavaMethodRef _java_Ljava_lang_Math_method_min_J_J_J ;
#define Java_java_lang_Math_nextAfter__DD _java_Ljava_lang_Math_method_nextAfter_D_D_D,2,27ll
extern JavaMethodRef _java_Ljava_lang_Math_method_nextAfter_D_D_D ;
#define Java_java_lang_Math_nextAfter__FD _java_Ljava_lang_Math_method_nextAfter_F_D_F,2,28ll
extern JavaMethodRef _java_Ljava_lang_Math_method_nextAfter_F_D_F ;
#define Java_java_lang_Math_nextUp__D _java_Ljava_lang_Math_method_nextUp_D_D,1,3ll
extern JavaMethodRef _java_Ljava_lang_Math_method_nextUp_D_D ;
#define Java_java_lang_Math_nextUp__F _java_Ljava_lang_Math_method_nextUp_F_F,1,4ll
extern JavaMethodRef _java_Ljava_lang_Math_method_nextUp_F_F ;
#define Java_java_lang_Math_random _java_Ljava_lang_Math_method_random_D,0,0ll
extern JavaMethodRef _java_Ljava_lang_Math_method_random_D ;
#define Java_java_lang_Math_round__D _java_Ljava_lang_Math_method_round_D_J,1,3ll
extern JavaMethodRef _java_Ljava_lang_Math_method_round_D_J ;
#define Java_java_lang_Math_round__F _java_Ljava_lang_Math_method_round_F_I,1,4ll
extern JavaMethodRef _java_Ljava_lang_Math_method_round_F_I ;
#define Java_java_lang_Math_scalb__DI _java_Ljava_lang_Math_method_scalb_D_I_D,2,11ll
extern JavaMethodRef _java_Ljava_lang_Math_method_scalb_D_I_D ;
#define Java_java_lang_Math_scalb__FI _java_Ljava_lang_Math_method_scalb_F_I_F,2,12ll
extern JavaMethodRef _java_Ljava_lang_Math_method_scalb_F_I_F ;
#define Java_java_lang_Math_signum__D _java_Ljava_lang_Math_method_signum_D_D,1,3ll
extern JavaMethodRef _java_Ljava_lang_Math_method_signum_D_D ;
#define Java_java_lang_Math_signum__F _java_Ljava_lang_Math_method_signum_F_F,1,4ll
extern JavaMethodRef _java_Ljava_lang_Math_method_signum_F_F ;
#define Java_java_lang_Math_toDegrees _java_Ljava_lang_Math_method_toDegrees_D_D,1,3ll
extern JavaMethodRef _java_Ljava_lang_Math_method_toDegrees_D_D ;
#define Java_java_lang_Math_toRadians _java_Ljava_lang_Math_method_toRadians_D_D,1,3ll
extern JavaMethodRef _java_Ljava_lang_Math_method_toRadians_D_D ;
#define Java_java_lang_Math_ulp__D _java_Ljava_lang_Math_method_ulp_D_D,1,3ll
extern JavaMethodRef _java_Ljava_lang_Math_method_ulp_D_D ;
#define Java_java_lang_Math_ulp__F _java_Ljava_lang_Math_method_ulp_F_F,1,4ll
extern JavaMethodRef _java_Ljava_lang_Math_method_ulp_F_F ;
#define Java_com_is2t_vm_support_lang_Systools_charValue _java_Lcom_is2t_vm_support_lang_Systools_method_charValue_I_C,1,1ll
extern JavaMethodRef _java_Lcom_is2t_vm_support_lang_Systools_method_charValue_I_C ;
#define Java_ej_microui_MicroUI_start _java_Lej_microui_MicroUI_method_start_V,0,0ll
extern JavaMethodRef _java_Lej_microui_MicroUI_method_start_V ;
#define Java_ej_microui_MicroUI_stop _java_Lej_microui_MicroUI_method_stop_V,0,0ll
extern JavaMethodRef _java_Lej_microui_MicroUI_method_stop_V ;
#define Java_ej_microui_MicroUI_checkRunning _java_Lej_microui_MicroUI_method_checkRunning_V,0,0ll
extern JavaMethodRef _java_Lej_microui_MicroUI_method_checkRunning_V ;
#define Java_ej_microui_event_generator_Buttons_isPressed _java_Lej_microui_event_generator_Buttons_method_isPressed_I_Z,1,1ll
extern JavaMethodRef _java_Lej_microui_event_generator_Buttons_method_isPressed_I_Z ;
#define Java_ej_microui_event_generator_Buttons_isReleased _java_Lej_microui_event_generator_Buttons_method_isReleased_I_Z,1,1ll
extern JavaMethodRef _java_Lej_microui_event_generator_Buttons_method_isReleased_I_Z ;
#define Java_ej_microui_event_generator_Buttons_isRepeated _java_Lej_microui_event_generator_Buttons_method_isRepeated_I_Z,1,1ll
extern JavaMethodRef _java_Lej_microui_event_generator_Buttons_method_isRepeated_I_Z ;
#define Java_ej_microui_event_generator_Buttons_isLong _java_Lej_microui_event_generator_Buttons_method_isLong_I_Z,1,1ll
extern JavaMethodRef _java_Lej_microui_event_generator_Buttons_method_isLong_I_Z ;
#define Java_ej_microui_event_generator_Buttons_isClicked _java_Lej_microui_event_generator_Buttons_method_isClicked_I_Z,1,1ll
extern JavaMethodRef _java_Lej_microui_event_generator_Buttons_method_isClicked_I_Z ;
#define Java_ej_microui_event_generator_Buttons_isDoubleClicked _java_Lej_microui_event_generator_Buttons_method_isDoubleClicked_I_Z,1,1ll
extern JavaMethodRef _java_Lej_microui_event_generator_Buttons_method_isDoubleClicked_I_Z ;
#define Java_ej_microui_event_generator_Buttons_getButtonID _java_Lej_microui_event_generator_Buttons_method_getButtonID_I_I,1,1ll
extern JavaMethodRef _java_Lej_microui_event_generator_Buttons_method_getButtonID_I_I ;
#define Java_ej_microui_event_generator_Buttons_getAction _java_Lej_microui_event_generator_Buttons_method_getAction_I_I,1,1ll
extern JavaMethodRef _java_Lej_microui_event_generator_Buttons_method_getAction_I_I ;
#define Java_ej_microui_event_generator_Buttons_buildEventData _java_Lej_microui_event_generator_Buttons_method_buildEventData_I_I_I,2,9ll
extern JavaMethodRef _java_Lej_microui_event_generator_Buttons_method_buildEventData_I_I_I ;
#define Java_ej_microui_PumpsPool_startAll _java_Lej_microui_PumpsPool_method_startAll_V,0,0ll
extern JavaMethodRef _java_Lej_microui_PumpsPool_method_startAll_V ;
#define Java_ej_microui_PumpsPool_stopAll _java_Lej_microui_PumpsPool_method_stopAll_V,0,0ll
extern JavaMethodRef _java_Lej_microui_PumpsPool_method_stopAll_V ;
#define Java_ej_microui_PumpsPool_areAllPumpsStopped _java_Lej_microui_PumpsPool_method_areAllPumpsStopped_Z,0,0ll
extern JavaMethodRef _java_Lej_microui_PumpsPool_method_areAllPumpsStopped_Z ;
#define Java_com_is2t_tools_ArrayTools_checkBounds___3BII _java_Lcom_is2t_tools_ArrayTools_method_checkBounds_AB_I_I_V,3,72ll
extern JavaMethodRef _java_Lcom_is2t_tools_ArrayTools_method_checkBounds_AB_I_I_V ;
#define Java_com_is2t_tools_ArrayTools_checkBounds__III _java_Lcom_is2t_tools_ArrayTools_method_checkBounds_I_I_I_V,3,73ll
extern JavaMethodRef _java_Lcom_is2t_tools_ArrayTools_method_checkBounds_I_I_I_V ;
#define Java_com_is2t_tools_ArrayTools_checkArrayBounds _java_Lcom_is2t_tools_ArrayTools_method_checkArrayBounds_I_I_I_V,3,73ll
extern JavaMethodRef _java_Lcom_is2t_tools_ArrayTools_method_checkArrayBounds_I_I_I_V ;
#define Java_com_is2t_tools_ArrayTools_checkStringBounds _java_Lcom_is2t_tools_ArrayTools_method_checkStringBounds_I_I_I_V,3,73ll
extern JavaMethodRef _java_Lcom_is2t_tools_ArrayTools_method_checkStringBounds_I_I_I_V ;
#define Java_com_is2t_tools_ArrayTools_checkBounds__IIII _java_Lcom_is2t_tools_ArrayTools_method_checkBounds_I_I_I_I_V,4,585ll
extern JavaMethodRef _java_Lcom_is2t_tools_ArrayTools_method_checkBounds_I_I_I_I_V ;
#define Java_com_is2t_tools_ArrayTools_remove___3III _java_Lcom_is2t_tools_ArrayTools_method_remove_AI_I_I_Z,3,72ll
extern JavaMethodRef _java_Lcom_is2t_tools_ArrayTools_method_remove_AI_I_I_Z ;
#define Java_ej_bon_Util_isInMission _java_Lej_bon_Util_method_isInMission_Z,0,0ll
extern JavaMethodRef _java_Lej_bon_Util_method_isInMission_Z ;
#define Java_ej_bon_Util_dynamicCodeAllowed _java_Lej_bon_Util_method_dynamicCodeAllowed_Z,0,0ll
extern JavaMethodRef _java_Lej_bon_Util_method_dynamicCodeAllowed_Z ;
#define Java_ej_bon_Util_dynamicCodeMemory _java_Lej_bon_Util_method_dynamicCodeMemory_I,0,0ll
extern JavaMethodRef _java_Lej_bon_Util_method_dynamicCodeMemory_I ;
#define Java_ej_bon_Util_dynamicCodeFreeMemory _java_Lej_bon_Util_method_dynamicCodeFreeMemory_I,0,0ll
extern JavaMethodRef _java_Lej_bon_Util_method_dynamicCodeFreeMemory_I ;
#define Java_ej_bon_Util_currentTimeMillis _java_Lej_bon_Util_method_currentTimeMillis_J,0,0ll
extern JavaMethodRef _java_Lej_bon_Util_method_currentTimeMillis_J ;
#define Java_ej_bon_Util_platformTimeMillis _java_Lej_bon_Util_method_platformTimeMillis_J,0,0ll
extern JavaMethodRef _java_Lej_bon_Util_method_platformTimeMillis_J ;
#define Java_ej_bon_Util_platformTimeNanos _java_Lej_bon_Util_method_platformTimeNanos_J,0,0ll
extern JavaMethodRef _java_Lej_bon_Util_method_platformTimeNanos_J ;
#define Java_ej_bon_Util_setCurrentTimeMillis__J _java_Lej_bon_Util_method_setCurrentTimeMillis_J_V,1,2ll
extern JavaMethodRef _java_Lej_bon_Util_method_setCurrentTimeMillis_J_V ;
#define Java_ej_microui_display_Display_isAMainGraphics _java_Lej_microui_display_Display_method_isAMainGraphics_I_Z,1,1ll
extern JavaMethodRef _java_Lej_microui_display_Display_method_isAMainGraphics_I_Z ;
#define Java_java_lang_Double_isInfinite__D _java_Ljava_lang_Double_method_isInfinite_D_Z,1,3ll
extern JavaMethodRef _java_Ljava_lang_Double_method_isInfinite_D_Z ;
#define Java_java_lang_Double_isNaN__D _java_Ljava_lang_Double_method_isNaN_D_Z,1,3ll
extern JavaMethodRef _java_Ljava_lang_Double_method_isNaN_D_Z ;
#define Java_java_lang_Double_compare _java_Ljava_lang_Double_method_compare_D_D_I,2,27ll
extern JavaMethodRef _java_Ljava_lang_Double_method_compare_D_D_I ;
#define Java_java_lang_Character_compare _java_Ljava_lang_Character_method_compare_C_C_I,2,9ll
extern JavaMethodRef _java_Ljava_lang_Character_method_compare_C_C_I ;
#define Java_java_lang_Character_digit__BI _java_Ljava_lang_Character_method_digit_B_I_I,2,9ll
extern JavaMethodRef _java_Ljava_lang_Character_method_digit_B_I_I ;
#define Java_java_lang_Character_digit__CI _java_Ljava_lang_Character_method_digit_C_I_I,2,9ll
extern JavaMethodRef _java_Ljava_lang_Character_method_digit_C_I_I ;
#define Java_java_lang_Character_forDigit _java_Ljava_lang_Character_method_forDigit_I_I_C,2,9ll
extern JavaMethodRef _java_Ljava_lang_Character_method_forDigit_I_I_C ;
#define Java_java_lang_Character_isDigit _java_Ljava_lang_Character_method_isDigit_C_Z,1,1ll
extern JavaMethodRef _java_Ljava_lang_Character_method_isDigit_C_Z ;
#define Java_java_lang_Character_isISOControl _java_Ljava_lang_Character_method_isISOControl_C_Z,1,1ll
extern JavaMethodRef _java_Ljava_lang_Character_method_isISOControl_C_Z ;
#define Java_java_lang_Character_isLowerCase _java_Ljava_lang_Character_method_isLowerCase_C_Z,1,1ll
extern JavaMethodRef _java_Ljava_lang_Character_method_isLowerCase_C_Z ;
#define Java_java_lang_Character_isSpaceChar _java_Ljava_lang_Character_method_isSpaceChar_C_Z,1,1ll
extern JavaMethodRef _java_Ljava_lang_Character_method_isSpaceChar_C_Z ;
#define Java_java_lang_Character_isUpperCase _java_Ljava_lang_Character_method_isUpperCase_C_Z,1,1ll
extern JavaMethodRef _java_Ljava_lang_Character_method_isUpperCase_C_Z ;
#define Java_java_lang_Character_isWhitespace _java_Ljava_lang_Character_method_isWhitespace_C_Z,1,1ll
extern JavaMethodRef _java_Ljava_lang_Character_method_isWhitespace_C_Z ;
#define Java_java_lang_Character_isStandardWhiteSpace _java_Ljava_lang_Character_method_isStandardWhiteSpace_C_Z,1,1ll
extern JavaMethodRef _java_Ljava_lang_Character_method_isStandardWhiteSpace_C_Z ;
#define Java_java_lang_Character_toLowerCase _java_Ljava_lang_Character_method_toLowerCase_C_C,1,1ll
extern JavaMethodRef _java_Ljava_lang_Character_method_toLowerCase_C_C ;
#define Java_java_lang_Character_toUpperCase _java_Ljava_lang_Character_method_toUpperCase_C_C,1,1ll
extern JavaMethodRef _java_Ljava_lang_Character_method_toUpperCase_C_C ;
#define Java_ej_microui_event_Event_getType _java_Lej_microui_event_Event_method_getType_I_I,1,1ll
extern JavaMethodRef _java_Lej_microui_event_Event_method_getType_I_I ;
#define Java_ej_microui_event_Event_getData _java_Lej_microui_event_Event_method_getData_I_I,1,1ll
extern JavaMethodRef _java_Lej_microui_event_Event_method_getData_I_I ;
#define Java_ej_microui_event_Event_getGeneratorID _java_Lej_microui_event_Event_method_getGeneratorID_I_I,1,1ll
extern JavaMethodRef _java_Lej_microui_event_Event_method_getGeneratorID_I_I ;
#define Java_ej_microui_display_Image_allocateImage _java_Lej_microui_display_Image_method_allocateImage_I_I_I_I,3,73ll
extern JavaMethodRef _java_Lej_microui_display_Image_method_allocateImage_I_I_I_I ;
#define Java_ej_microui_display_Image_openOffscreen _java_Lej_microui_display_Image_method_openOffscreen_I_I_I_I,3,73ll
extern JavaMethodRef _java_Lej_microui_display_Image_method_openOffscreen_I_I_I_I ;
#define Java_ej_microui_display_Image_checkError _java_Lej_microui_display_Image_method_checkError_I_I,1,1ll
extern JavaMethodRef _java_Lej_microui_display_Image_method_checkError_I_I ;
#define Java_ej_microui_display_GraphicsContext_getAlpha _java_Lej_microui_display_GraphicsContext_method_getAlpha_I_I,1,1ll
extern JavaMethodRef _java_Lej_microui_display_GraphicsContext_method_getAlpha_I_I ;
#define Java_ej_microui_display_GraphicsContext_computeXTopLeftCorner _java_Lej_microui_display_GraphicsContext_method_computeXTopLeftCorner_I_I_I_I,3,73ll
extern JavaMethodRef _java_Lej_microui_display_GraphicsContext_method_computeXTopLeftCorner_I_I_I_I ;
#define Java_ej_microui_display_GraphicsContext_computeYTopLeftCorner _java_Lej_microui_display_GraphicsContext_method_computeYTopLeftCorner_I_I_I_I,3,73ll
extern JavaMethodRef _java_Lej_microui_display_GraphicsContext_method_computeYTopLeftCorner_I_I_I_I ;
#define Java_java_lang_AbstractMethodError_throwAbstractMethodError _java_Ljava_lang_AbstractMethodError_method_throwAbstractMethodError_V,0,0ll
extern JavaMethodRef _java_Ljava_lang_AbstractMethodError_method_throwAbstractMethodError_V ;
#define Java_java_lang_Float_compare _java_Ljava_lang_Float_method_compare_F_F_I,2,36ll
extern JavaMethodRef _java_Ljava_lang_Float_method_compare_F_F_I ;
#define Java_java_lang_Float_isInfinite__F _java_Ljava_lang_Float_method_isInfinite_F_Z,1,4ll
extern JavaMethodRef _java_Ljava_lang_Float_method_isInfinite_F_Z ;
#define Java_java_lang_Float_isNaN__F _java_Ljava_lang_Float_method_isNaN_F_Z,1,4ll
extern JavaMethodRef _java_Ljava_lang_Float_method_isNaN_F_Z ;
#define Java_java_lang_Thread_sleep__J _java_Ljava_lang_Thread_method_sleep_J_V,1,2ll
extern JavaMethodRef _java_Ljava_lang_Thread_method_sleep_J_V ;
#define Java_java_lang_Thread_sleep__JI _java_Ljava_lang_Thread_method_sleep_J_I_V,2,10ll
extern JavaMethodRef _java_Ljava_lang_Thread_method_sleep_J_I_V ;
#define Java_java_lang_Thread_updateThreadCounters _java_Ljava_lang_Thread_method_updateThreadCounters_V,0,0ll
extern JavaMethodRef _java_Ljava_lang_Thread_method_updateThreadCounters_V ;
#define Java_java_lang_Thread_resetPeakThreadCount _java_Ljava_lang_Thread_method_resetPeakThreadCount_V,0,0ll
extern JavaMethodRef _java_Ljava_lang_Thread_method_resetPeakThreadCount_V ;
#define Java_java_lang_Thread_yield _java_Ljava_lang_Thread_method_yield_V,0,0ll
extern JavaMethodRef _java_Ljava_lang_Thread_method_yield_V ;
#define Java_java_lang_Thread_callWrapper _java_Ljava_lang_Thread_method_callWrapper_V,0,0ll
extern JavaMethodRef _java_Ljava_lang_Thread_method_callWrapper_V ;
#define Java_java_lang_Thread_clinitWrapper _java_Ljava_lang_Thread_method_clinitWrapper_I_V,1,1ll
extern JavaMethodRef _java_Ljava_lang_Thread_method_clinitWrapper_I_V ;
#define Java_java_lang_Thread_dumpStack _java_Ljava_lang_Thread_method_dumpStack_V,0,0ll
extern JavaMethodRef _java_Ljava_lang_Thread_method_dumpStack_V ;
#define Java_java_lang_Thread_checkPermissionGetStackTrace _java_Ljava_lang_Thread_method_checkPermissionGetStackTrace_V,0,0ll
extern JavaMethodRef _java_Ljava_lang_Thread_method_checkPermissionGetStackTrace_V ;
#define Java_java_lang_Integer_compare _java_Ljava_lang_Integer_method_compare_I_I_I,2,9ll
extern JavaMethodRef _java_Ljava_lang_Integer_method_compare_I_I_I ;
#define Java_java_lang_Integer_rotateLeft _java_Ljava_lang_Integer_method_rotateLeft_I_I_I,2,9ll
extern JavaMethodRef _java_Ljava_lang_Integer_method_rotateLeft_I_I_I ;
#define Java_java_lang_Integer_rotateRight _java_Ljava_lang_Integer_method_rotateRight_I_I_I,2,9ll
extern JavaMethodRef _java_Ljava_lang_Integer_method_rotateRight_I_I_I ;
#define Java_java_lang_Integer_signum _java_Ljava_lang_Integer_method_signum_I_I,1,1ll
extern JavaMethodRef _java_Ljava_lang_Integer_method_signum_I_I ;
#define Java_com_is2t_debug_Assert_check__Z _java_Lcom_is2t_debug_Assert_method_check_Z_V,1,1ll
extern JavaMethodRef _java_Lcom_is2t_debug_Assert_method_check_Z_V ;
#define Java_test_TestLCD03_class$ _java_Ltest_TestLCD03_method_class$_V,0,0ll
extern JavaMethodRef _java_Ltest_TestLCD03_method_class$_V ;
#define Java_ej_microui_display_Font_getStylesOrFilters _java_Lej_microui_display_Font_method_getStylesOrFilters_I_I_I_I,3,73ll
extern JavaMethodRef _java_Lej_microui_display_Font_method_getStylesOrFilters_I_I_I_I ;
#define Java_ej_microui_display_Font_isStyle _java_Lej_microui_display_Font_method_isStyle_I_I_Z,2,9ll
extern JavaMethodRef _java_Lej_microui_display_Font_method_isStyle_I_I_Z ;
#define Java_ej_microui_display_Font_checkFontRuntimeError _java_Lej_microui_display_Font_method_checkFontRuntimeError_I_I,1,1ll
extern JavaMethodRef _java_Lej_microui_display_Font_method_checkFontRuntimeError_I_I ;
#define Java_com_is2t_tools_GeometryTools_checkScanBounds _java_Lcom_is2t_tools_GeometryTools_method_checkScanBounds_I_I_I_I_I_V,5,4681ll
extern JavaMethodRef _java_Lcom_is2t_tools_GeometryTools_method_checkScanBounds_I_I_I_I_I_V ;
#define Java_com_is2t_tools_GeometryTools_contains _java_Lcom_is2t_tools_GeometryTools_method_contains_I_I_I_I_I_I_Z,6,37449ll
extern JavaMethodRef _java_Lcom_is2t_tools_GeometryTools_method_contains_I_I_I_I_I_I_Z ;
#define Java_com_is2t_tools_BitFieldHelper_setBooleanProperty__IZI _java_Lcom_is2t_tools_BitFieldHelper_method_setBooleanProperty_I_Z_I_I,3,73ll
extern JavaMethodRef _java_Lcom_is2t_tools_BitFieldHelper_method_setBooleanProperty_I_Z_I_I ;
#define Java_com_is2t_tools_BitFieldHelper_setBooleanProperty__II _java_Lcom_is2t_tools_BitFieldHelper_method_setBooleanProperty_I_I_I,2,9ll
extern JavaMethodRef _java_Lcom_is2t_tools_BitFieldHelper_method_setBooleanProperty_I_I_I ;
#define Java_com_is2t_tools_BitFieldHelper_unsetBooleanProperty _java_Lcom_is2t_tools_BitFieldHelper_method_unsetBooleanProperty_I_I_I,2,9ll
extern JavaMethodRef _java_Lcom_is2t_tools_BitFieldHelper_method_unsetBooleanProperty_I_I_I ;
#define Java_com_is2t_tools_BitFieldHelper_getBooleanProperty _java_Lcom_is2t_tools_BitFieldHelper_method_getBooleanProperty_I_I_Z,2,9ll
extern JavaMethodRef _java_Lcom_is2t_tools_BitFieldHelper_method_getBooleanProperty_I_I_Z ;
#define Java_com_is2t_tools_BitFieldHelper_setIntProperty _java_Lcom_is2t_tools_BitFieldHelper_method_setIntProperty_I_I_I_I_I,4,585ll
extern JavaMethodRef _java_Lcom_is2t_tools_BitFieldHelper_method_setIntProperty_I_I_I_I_I ;
#define Java_com_is2t_tools_BitFieldHelper_getIntProperty _java_Lcom_is2t_tools_BitFieldHelper_method_getIntProperty_I_I_I_I,3,73ll
extern JavaMethodRef _java_Lcom_is2t_tools_BitFieldHelper_method_getIntProperty_I_I_I_I ;
#define Java_java_lang_Boolean_compare _java_Ljava_lang_Boolean_method_compare_Z_Z_I,2,9ll
extern JavaMethodRef _java_Ljava_lang_Boolean_method_compare_Z_Z_I ;
#define Java_java_lang_Long_compare _java_Ljava_lang_Long_method_compare_J_J_I,2,18ll
extern JavaMethodRef _java_Ljava_lang_Long_method_compare_J_J_I ;
#define Java_java_lang_Long_rotateLeft _java_Ljava_lang_Long_method_rotateLeft_J_I_J,2,10ll
extern JavaMethodRef _java_Ljava_lang_Long_method_rotateLeft_J_I_J ;
#define Java_java_lang_Long_rotateRight _java_Ljava_lang_Long_method_rotateRight_J_I_J,2,10ll
extern JavaMethodRef _java_Ljava_lang_Long_method_rotateRight_J_I_J ;
#define Java_java_lang_Long_signum _java_Ljava_lang_Long_method_signum_J_I,1,2ll
extern JavaMethodRef _java_Ljava_lang_Long_method_signum_J_I ;
#define Java_ej_bon_CurrentTime_setAppTime _java_Lej_bon_CurrentTime_method_setAppTime_J_V,1,2ll
extern JavaMethodRef _java_Lej_bon_CurrentTime_method_setAppTime_J_V ;
#define Java_com_is2t_vm_support_util_GregorianCalendar_isBisextilYear _java_Lcom_is2t_vm_support_util_GregorianCalendar_method_isBisextilYear_I_Z,1,1ll
extern JavaMethodRef _java_Lcom_is2t_vm_support_util_GregorianCalendar_method_isBisextilYear_I_Z ;
#define Java_com_is2t_vm_support_util_GregorianCalendar_getNbDaysInYear _java_Lcom_is2t_vm_support_util_GregorianCalendar_method_getNbDaysInYear_I_I,1,1ll
extern JavaMethodRef _java_Lcom_is2t_vm_support_util_GregorianCalendar_method_getNbDaysInYear_I_I ;
#define Java_com_is2t_vm_support_util_GregorianCalendar_getNbOfDays _java_Lcom_is2t_vm_support_util_GregorianCalendar_method_getNbOfDays_I_Z_I,2,9ll
extern JavaMethodRef _java_Lcom_is2t_vm_support_util_GregorianCalendar_method_getNbOfDays_I_Z_I ;
#define Java_com_is2t_vm_support_util_GregorianCalendar_getFirstMonthDay _java_Lcom_is2t_vm_support_util_GregorianCalendar_method_getFirstMonthDay_I_I_I,2,9ll
extern JavaMethodRef _java_Lcom_is2t_vm_support_util_GregorianCalendar_method_getFirstMonthDay_I_I_I ;
